import Head from "next/head";
import Script from "next/script";
import { ThemeProvider } from "components";

function App({ Component, pageProps }) {
  //google карта
  //        <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyfYnJ4UClpzA9ywXK01nW0FzebwUwDNI&v=weekly"></script>

  return (
    <>
      <Head>
        <title>Color Department — Los Angeles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider>
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
}

export default App;
